Repository unifiedjs/unified, pull requests merged in 2023-08, with the labels that each got.

#202 Add useful error on empty presets
  lib/index.js
  test/use.js
Labels: 🦋 type/enhancement, 🧑 semver/major, 👍 phase/yes

#216 Update `typescript`
  package.json
  test/process.js
  test/run.js
  test/use.js
  tsconfig.json
Labels: ☂️ area/types, 🤞 phase/open

#225 Fix some typos
  readme.md
  script/fix-types.js
Labels: 🤞 phase/open
